# docker swarm 互換モードは3を指定する
version: "3"
services:
  haproxy:
    image: dockercloud/haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      # 特定のコンテナをクラスタ上の全ノードに配位できる設定
      mode: global
      # managerノードだけに配置されるように設定
      placement:
        constraints: [node.role == manager]
    networks:
      - ch03
    ports:
      - 80:80
      - 1936:1936 # for stats page (basic auth. stats:stats)

networks:
  ch03:
    external: true